### ISSUE TITLE
When I run ./configure, error : syntax error near unexpected token `USB,'

### ISSUE THREAD

**Issue by stanleyseow** [riscv-mcu/gd32-dfu-utils#7]
OS : Ubuntu 1804

I hv install libusb :
ii  libgusb2:amd64                             0.2.11-1                                         amd64        GLib wrapper around libusb1
ii  libusb-1.0-0:amd64                         2:1.0.21-2                                       amd64        userspace USB programming library
ii  libusb-1.0-0-dev:amd64                     2:1.0.21-2                                       amd64        userspace USB programming library development files

Configure output : 
stan@ubuntu:~/gd32-dfu-utils$ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/home/stanley/gd32-dfu-utils/m4/missing: Unknown `--is-lightweight' option
Try `/home/stanley/gd32-dfu-utils/m4/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for libusb_init in -lusb... no
./configure: line 3954: syntax error near unexpected token `USB,'
./configure: line 3954: `    PKG_CHECK_MODULES(USB, libusb-1.0 >= 1.0.0,,'

**Comment by elfmimi** [comment]
Try install pkg-config and automake .
and s/1.14/1.15/ in configure .

**Comment by stanleyseow** [comment]
Thanks, this package was missing **pkg-config**
Compilation done ...
