### ISSUE TITLE
Please upstream these quirk fixes

### ISSUE THREAD

**Issue by JeroenVreeken** [riscv-mcu/gd32-dfu-utils#8]
Please submit these fixes to the upstream dfu project.
It took me a while to figure out the mainline dfu-util does not properly work with the gd32 chips.
Not upstreaming means I need a seperate version just for this chip.

**Comment by elfmimi** [comment]
@JeroenVreeken which version did you try? dfu-util 0.10 should work fine.
well, it may spit error at the end but you can ignore it.

**Comment by JeroenVreeken** [comment]
Indeed, I had not noticed the new release yet!
